image: node:latest

before_script:
  - 'which ssh-agent || ( apt-get update -y && apt-get install openssh-client -y )'

stages:
  - build
  - test
  - deploy

lint:
  stage: build
  script:
    - npm ci

lint:
  stage: test
  script:
    - npm run lint

deployToAWS:
  only:
    # - master
    - developer
  stage: deploy
  script:
    - bash deploy.sh
